### ISSUE TITLE
need to create mutability tests

### ISSUE THREAD

**Issue by eeeeaaii** [eeeeaaii/vodka#203]
example:
bind @foo to point to a mutable doc you just typed in
@foo will point to a immutable copy
make @bar point to a mutable version by using the copy builtin
write the statement "bind @foo @bar" and don't eval @bar, just eval the whole bind statement
in that case @foo will refer to the mutable copy
again write "bind @foo @bar" and eval @bar first then eval the statement
now @foo will refer to a immutable copy again

**Comment by bar** [comment]
@eeeeaaii I believe you meant to tag someone else, right?

**Comment by eeeeaaii** [comment]
> @eeeeaaii I believe you meant to tag someone else, right?

Right, sorry, the @ symbol is used in Vodka to indicate something is a symbol, I didn't realize it was also used in github comments to tag people. I'll try to be more careful in the future.
